#line 2 "magic-interpreter-lexer.c"

#line 4 "magic-interpreter-lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer magic_frontend__create_buffer
#define yy_delete_buffer magic_frontend__delete_buffer
#define yy_flex_debug magic_frontend__flex_debug
#define yy_init_buffer magic_frontend__init_buffer
#define yy_flush_buffer magic_frontend__flush_buffer
#define yy_load_buffer_state magic_frontend__load_buffer_state
#define yy_switch_to_buffer magic_frontend__switch_to_buffer
#define yyin magic_frontend_in
#define yyleng magic_frontend_leng
#define yylex magic_frontend_lex
#define yylineno magic_frontend_lineno
#define yyout magic_frontend_out
#define yyrestart magic_frontend_restart
#define yytext magic_frontend_text
#define yywrap magic_frontend_wrap
#define yyalloc magic_frontend_alloc
#define yyrealloc magic_frontend_realloc
#define yyfree magic_frontend_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE magic_frontend_restart(magic_frontend_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int magic_frontend_leng;

extern FILE *magic_frontend_in, *magic_frontend_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE magic_frontend_lex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-magic_frontend_lineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < magic_frontend_leng; ++yyl )\
                    if ( magic_frontend_text[yyl] == '\n' )\
                        --magic_frontend_lineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up magic_frontend_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up magic_frontend_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via magic_frontend_restart()), so that the user can continue scanning by
	 * just pointing magic_frontend_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when magic_frontend_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int magic_frontend_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow magic_frontend_wrap()'s to do buffer switches
 * instead of setting up a fresh magic_frontend_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void magic_frontend_restart (FILE *input_file  );
void magic_frontend__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE magic_frontend__create_buffer (FILE *file,int size  );
void magic_frontend__delete_buffer (YY_BUFFER_STATE b  );
void magic_frontend__flush_buffer (YY_BUFFER_STATE b  );
void magic_frontend_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void magic_frontend_pop_buffer_state (void );

static void magic_frontend_ensure_buffer_stack (void );
static void magic_frontend__load_buffer_state (void );
static void magic_frontend__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER magic_frontend__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE magic_frontend__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE magic_frontend__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE magic_frontend__scan_bytes (yyconst char *bytes,int len  );

void *magic_frontend_alloc (yy_size_t  );
void *magic_frontend_realloc (void *,yy_size_t  );
void magic_frontend_free (void *  );

#define yy_new_buffer magic_frontend__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        magic_frontend_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            magic_frontend__create_buffer(magic_frontend_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        magic_frontend_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            magic_frontend__create_buffer(magic_frontend_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define magic_frontend_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *magic_frontend_in = (FILE *) 0, *magic_frontend_out = (FILE *) 0;

typedef int yy_state_type;

extern int magic_frontend_lineno;

int magic_frontend_lineno = 1;

extern char *magic_frontend_text;
#define yytext_ptr magic_frontend_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up magic_frontend_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	magic_frontend_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 85
#define YY_END_OF_BUFFER 86
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[238] =
    {   0,
        0,    0,   86,   84,   83,   83,   84,   84,   84,   23,
       33,   17,   18,   21,   19,   28,   20,   35,   22,   78,
       78,   27,   26,   14,    9,   13,   29,   80,   80,   80,
       80,    7,   80,   80,   80,   80,   80,    5,   80,   80,
       80,    1,   80,    3,   31,   32,   34,   84,   30,   12,
        0,   77,    0,    0,   81,   24,   78,    0,    0,   36,
       16,   11,   10,   51,   15,   37,   80,   80,   80,   80,
       80,   80,   74,   80,   80,   80,   80,   69,   49,   80,
       80,   80,   80,    6,   80,    4,   40,   65,   80,   80,
        8,   80,   80,   80,   80,    2,   80,   80,   80,   41,

       80,    0,    0,   76,   25,    0,   77,    0,    0,   82,
       79,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   50,   80,   73,   48,   80,   80,   66,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,    0,    0,   76,   80,   80,   80,   80,   39,   80,
       80,   80,   80,   80,   71,   80,   80,   80,   56,   80,
       80,   80,   80,   58,   80,   80,   80,   80,   70,   80,
       75,   59,   62,   80,   60,   80,   80,   80,   64,   80,
       80,   80,   45,   80,   80,   80,   80,   47,   80,   80,
       80,   80,   80,   80,   80,   80,   61,   67,   80,   80,

       80,   80,   44,   52,   68,   80,   80,   80,   80,   80,
       80,   72,   80,   80,   53,   80,   42,   80,   57,   80,
       80,   46,   80,   80,   63,   54,   80,   38,   80,   55,
       80,   80,   80,   80,   80,   43,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    1,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       42,   43,   44,   45,   46,   35,   47,   35,   48,   35,
       49,   50,   51,   52,   24,    1,   53,   53,   53,   53,

       53,   53,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   54,
       35,   35,   55,   56,   57,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[58] =
    {   0,
        1,    1,    1,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    1,    1,    3,    3,    1,    1,
        1,    1,    1,    2,    1,    3,    3,    3,    3,    3,
        3,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1,
        1,    1,    3,    2,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[246] =
    {   0,
        0,    0,  287,  288,  288,  288,  264,   53,  282,  288,
      276,  288,  288,  288,  288,  288,   42,  288,  267,   44,
       46,  288,  288,   44,   46,   48,  288,   45,  239,   47,
      241,   43,  240,    0,   44,   46,   51,   48,  236,   51,
      248,   63,   76,  251,  288,  288,  288,   35,  220,  288,
       76,  288,  102,  272,  288,  288,   83,  271,    0,  288,
      288,  288,  288,  288,  288,  288,    0,  233,   66,  242,
       75,   75,    0,  240,  226,   86,  226,    0,    0,  223,
      239,  227,  238,    0,  225,    0,    0,    0,  223,  220,
        0,  224,  226,  229,  215,    0,  214,  219,  225,  207,

      219,   67,   86,  288,  288,   79,  113,  118,  249,  288,
        0,  208,  211,  206,  222,  210,  201,  219,  203,  199,
      212,  211,    0,  206,  209,    0,  212,  211,    0,  198,
      207,  188,  203,  191,  194,  196,  197,  198,  188,  200,
      180,   75,  119,   77,  179,  194,  188,  185,    0,  175,
      182,  178,  172,  188,    0,  170,  188,  176,    0,  186,
      181,  176,  170,    0,  171,  168,  176,  164,    0,  161,
        0,    0,    0,  171,    0,  168,  153,  161,    0,  154,
      150,  169,    0,  143,  145,  130,  127,    0,  139,  125,
      127,  137,  133,  126,  118,  131,    0,    0,  127,  125,

      112,  127,    0,    0,    0,  113,  111,  124,  123,  106,
      111,    0,  121,  105,    0,  102,    0,  103,    0,  101,
       99,    0,  112,  127,    0,    0,   96,    0,  113,    0,
       99,  109,  102,   93,   87,    0,  288,  176,  179,  181,
      184,  187,  190,  125,  193
    } ;

static yyconst flex_int16_t yy_def[246] =
    {   0,
      237,    1,  237,  237,  237,  237,  237,  238,  239,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  237,  237,  237,  241,  237,  237,
      238,  237,  242,  239,  237,  237,  237,  243,  244,  237,
      237,  237,  237,  237,  237,  237,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,

      240,  241,  245,  237,  237,  238,  238,  242,  243,  237,
      244,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  241,  245,  241,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,

      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,    0,  237,  237,  237,
      237,  237,  237,  237,  237
    } ;

static yyconst flex_int16_t yy_nxt[346] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,    4,   27,   28,   29,   30,   31,   32,
       33,   34,   34,   35,   34,   34,   36,   37,   38,   39,
       40,   34,   41,   42,   43,   34,   44,   34,   45,    4,
       46,   47,   34,   34,   48,   49,    4,   52,   57,   57,
       57,   57,   57,   57,   60,   61,   62,   63,   64,   65,
       66,   68,   71,   74,   78,   80,   82,   84,   88,   75,
       52,   76,   79,   52,  103,   81,   72,   85,  102,   69,
       83,  104,   91,   89,   86,  113,   92,   59,   93,   57,

       57,   97,   53,   94,   51,   98,  107,   95,   99,   96,
      114,  116,  119,  120,  123,  100,  103,   52,  117,  118,
       51,  102,  107,  104,  103,   53,  103,  111,   53,  236,
      124,  104,  235,  104,  234,  143,  233,  232,  231,  230,
      229,  228,  144,  227,  226,  225,  224,  223,  222,  221,
      220,  108,  219,  218,  217,  216,  215,  214,  213,  212,
      211,  210,   53,  209,  208,  207,  206,  108,  143,  205,
      204,  203,  202,  201,  200,  144,   51,   51,   51,   54,
       54,   54,   67,   67,  102,  102,  102,  106,  106,  106,
      109,  109,  109,  142,  142,  142,  199,  198,  197,  196,

      195,  194,  193,  192,  191,  190,  189,  188,  187,  186,
      185,  184,  183,  182,  181,  180,  179,  178,  177,  176,
      175,  174,  173,  172,  171,  170,  169,  168,  167,  166,
      165,  164,  163,  162,  161,  160,  159,  158,  157,  156,
      155,  154,  153,  152,  151,  150,  149,  148,  147,  146,
      145,  110,  141,  140,  139,  138,  137,  136,  135,  134,
      133,  132,  131,  130,  129,  128,  127,  126,  125,  122,
      121,  115,  112,  110,   55,  105,  101,   90,   87,   77,
       73,   70,   58,   56,   55,   50,  237,    3,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,

      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237
    } ;

static yyconst flex_int16_t yy_chk[346] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    8,   17,   17,
       20,   20,   21,   21,   24,   24,   24,   25,   25,   26,
       26,   28,   30,   32,   35,   36,   37,   38,   40,   32,
       51,   32,   35,  106,   48,   36,   30,   38,  103,   28,
       37,   48,   42,   40,   38,   69,   42,   20,   42,   57,

       57,   43,    8,   42,   53,   43,   53,   42,   43,   42,
       69,   71,   72,   72,   76,   43,  102,  107,   71,   71,
      108,  143,  108,  102,  142,   51,  144,  244,  106,  235,
       76,  142,  234,  144,  233,  103,  232,  231,  229,  227,
      224,  223,  103,  221,  220,  218,  216,  214,  213,  211,
      210,   53,  209,  208,  207,  206,  202,  201,  200,  199,
      196,  195,  107,  194,  193,  192,  191,  108,  143,  190,
      189,  187,  186,  185,  184,  143,  238,  238,  238,  239,
      239,  239,  240,  240,  241,  241,  241,  242,  242,  242,
      243,  243,  243,  245,  245,  245,  182,  181,  180,  178,

      177,  176,  174,  170,  168,  167,  166,  165,  163,  162,
      161,  160,  158,  157,  156,  154,  153,  152,  151,  150,
      148,  147,  146,  145,  141,  140,  139,  138,  137,  136,
      135,  134,  133,  132,  131,  130,  128,  127,  125,  124,
      122,  121,  120,  119,  118,  117,  116,  115,  114,  113,
      112,  109,  101,  100,   99,   98,   97,   95,   94,   93,
       92,   90,   89,   85,   83,   82,   81,   80,   77,   75,
       74,   70,   68,   58,   54,   49,   44,   41,   39,   33,
       31,   29,   19,   11,    9,    7,    3,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,

      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  237,  237
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[86] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 
    0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int magic_frontend__flex_debug;
int magic_frontend__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *magic_frontend_text;
#line 1 "magic-interpreter.l"
#line 2 "magic-interpreter.l"
#include "magic-interpreter.h"
#include "magic-interpreter-parser.h"

#ifdef HEADING
#  undef HEADING
#endif

#define FIXLOC magic_frontend_lloc.first_line = magic_frontend_lineno

#define HEADING(dir) { magic_frontend_lval.i = dir; FIXLOC; return DIR; }

#define YY_NO_INPUT 1
#line 664 "magic-interpreter-lexer.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int magic_frontend_lex_destroy (void );

int magic_frontend_get_debug (void );

void magic_frontend_set_debug (int debug_flag  );

YY_EXTRA_TYPE magic_frontend_get_extra (void );

void magic_frontend_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *magic_frontend_get_in (void );

void magic_frontend_set_in  (FILE * in_str  );

FILE *magic_frontend_get_out (void );

void magic_frontend_set_out  (FILE * out_str  );

int magic_frontend_get_leng (void );

char *magic_frontend_get_text (void );

int magic_frontend_get_lineno (void );

void magic_frontend_set_lineno (int line_number  );

YYSTYPE * magic_frontend_get_lval (void );

void magic_frontend_set_lval (YYSTYPE * yylval_param  );

       YYLTYPE *magic_frontend_get_lloc (void );
    
        void magic_frontend_set_lloc (YYLTYPE * yylloc_param  );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int magic_frontend_wrap (void );
#else
extern int magic_frontend_wrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( magic_frontend_text, magic_frontend_leng, 1, magic_frontend_out )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( magic_frontend_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( magic_frontend_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, magic_frontend_in))==0 && ferror(magic_frontend_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(magic_frontend_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int magic_frontend_lex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param );

#define YY_DECL int magic_frontend_lex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param )
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after magic_frontend_text and magic_frontend_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
        YYSTYPE * yylval;
    
        YYLTYPE * yylloc;
    
#line 22 "magic-interpreter.l"


#line 862 "magic-interpreter-lexer.c"

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! magic_frontend_in )
			magic_frontend_in = stdin;

		if ( ! magic_frontend_out )
			magic_frontend_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			magic_frontend_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				magic_frontend__create_buffer(magic_frontend_in,YY_BUF_SIZE );
		}

		magic_frontend__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of magic_frontend_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 238 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 288 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < magic_frontend_leng; ++yyl )
				if ( magic_frontend_text[yyl] == '\n' )
					   
    magic_frontend_lineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 24 "magic-interpreter.l"
HEADING(0);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 25 "magic-interpreter.l"
HEADING(1);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 26 "magic-interpreter.l"
HEADING(2);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 27 "magic-interpreter.l"
HEADING(3);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 28 "magic-interpreter.l"
HEADING(4);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 29 "magic-interpreter.l"
HEADING(5);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 30 "magic-interpreter.l"
HEADING(6);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 31 "magic-interpreter.l"
HEADING(7);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 32 "magic-interpreter.l"
{FIXLOC; return '=';}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 33 "magic-interpreter.l"
{FIXLOC; return EQ;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 34 "magic-interpreter.l"
{FIXLOC; return NEQ;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 35 "magic-interpreter.l"
{FIXLOC; return NEQ;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 36 "magic-interpreter.l"
{FIXLOC; return '>';}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 37 "magic-interpreter.l"
{FIXLOC; return '<';}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 38 "magic-interpreter.l"
{FIXLOC; return GTE;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 39 "magic-interpreter.l"
{FIXLOC; return LTE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 40 "magic-interpreter.l"
{FIXLOC; return '(';}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 41 "magic-interpreter.l"
{FIXLOC; return ')';}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 42 "magic-interpreter.l"
{FIXLOC; return '+';}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 43 "magic-interpreter.l"
{FIXLOC; return '-';}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 44 "magic-interpreter.l"
{FIXLOC; return '*';}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 45 "magic-interpreter.l"
{FIXLOC; return '/';}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 46 "magic-interpreter.l"
{FIXLOC; return '%';}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 47 "magic-interpreter.l"
{FIXLOC; return ANDAND;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 48 "magic-interpreter.l"
{FIXLOC; return OROR;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 49 "magic-interpreter.l"
{FIXLOC; return ';';}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 50 "magic-interpreter.l"
{FIXLOC; return ':';}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 51 "magic-interpreter.l"
{FIXLOC; return ',';}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 52 "magic-interpreter.l"
{FIXLOC; return '@';}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 53 "magic-interpreter.l"
{FIXLOC; return '|';}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 54 "magic-interpreter.l"
{FIXLOC; return '[';}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 55 "magic-interpreter.l"
{FIXLOC; return ']';}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 56 "magic-interpreter.l"
{FIXLOC; return '&';}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 57 "magic-interpreter.l"
{FIXLOC; return '^';}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 58 "magic-interpreter.l"
{FIXLOC; return '.';}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 59 "magic-interpreter.l"
{FIXLOC; return SHL;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 60 "magic-interpreter.l"
{FIXLOC; return SHR;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 61 "magic-interpreter.l"
{FIXLOC; return PROCEDURE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 62 "magic-interpreter.l"
{FIXLOC; return CALL;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 63 "magic-interpreter.l"
{FIXLOC; return OR;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 64 "magic-interpreter.l"
{FIXLOC; return TO;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 65 "magic-interpreter.l"
{FIXLOC; return TOWARDS;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 66 "magic-interpreter.l"
{FIXLOC; return TELEPORT_ANCHOR;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 67 "magic-interpreter.l"
{FIXLOC; return SILENT;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 68 "magic-interpreter.l"
{FIXLOC; return LOCAL;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 69 "magic-interpreter.l"
{FIXLOC; return NONMAGIC;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 70 "magic-interpreter.l"
{FIXLOC; return SPELL;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 71 "magic-interpreter.l"
{FIXLOC; return LET;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 72 "magic-interpreter.l"
{FIXLOC; return IN;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 73 "magic-interpreter.l"
{FIXLOC; return END;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 74 "magic-interpreter.l"
{FIXLOC; return DARROW;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 75 "magic-interpreter.l"
{FIXLOC; return STRING_TY;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 76 "magic-interpreter.l"
{FIXLOC; return REQUIRE;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 77 "magic-interpreter.l"
{FIXLOC; return CATALYSTS;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 78 "magic-interpreter.l"
{FIXLOC; return COMPONENTS;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 79 "magic-interpreter.l"
{FIXLOC; return MANA;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 80 "magic-interpreter.l"
{FIXLOC; return CASTTIME;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 81 "magic-interpreter.l"
{FIXLOC; return SKIP;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 82 "magic-interpreter.l"
{FIXLOC; return ABORT;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 83 "magic-interpreter.l"
{FIXLOC; return BREAK;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 84 "magic-interpreter.l"
{FIXLOC; return EFFECT;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 85 "magic-interpreter.l"
{FIXLOC; return ATEND;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 86 "magic-interpreter.l"
{FIXLOC; return ATTRIGGER;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 87 "magic-interpreter.l"
{FIXLOC; return CONST;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 88 "magic-interpreter.l"
{FIXLOC; return PC_F;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 89 "magic-interpreter.l"
{FIXLOC; return MOB_F;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 90 "magic-interpreter.l"
{FIXLOC; return ENTITY_F;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 91 "magic-interpreter.l"
{FIXLOC; return TARGET_F;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 92 "magic-interpreter.l"
{FIXLOC; return IF;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 93 "magic-interpreter.l"
{FIXLOC; return THEN;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 94 "magic-interpreter.l"
{FIXLOC; return ELSE;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 95 "magic-interpreter.l"
{FIXLOC; return FOREACH;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 96 "magic-interpreter.l"
{FIXLOC; return FOR;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 97 "magic-interpreter.l"
{FIXLOC; return DO;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 98 "magic-interpreter.l"
{FIXLOC; return SLEEP;}
	YY_BREAK
case 76:
/* rule 76 can match eol */
YY_RULE_SETUP
#line 100 "magic-interpreter.l"
{ char *string = strdup(magic_frontend_text);
                   magic_frontend_lval.s = string;
		   FIXLOC;
                   return SCRIPT_DATA;
                   }
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 106 "magic-interpreter.l"
{ char *string = strdup(magic_frontend_text + 1);
                   char *src = string;
                   char *dst = string;
                   while (*src && *src != '"')
                       if (*src == '\\') {
                           *dst++ = src[1];
                           src += 2;
                       } else
                           *dst++ = *src++;
                   *dst = '\0'; /* terminate */
                   magic_frontend_lval.s = string;
		   FIXLOC;
                   return STRING;
                   }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 121 "magic-interpreter.l"
{ magic_frontend_lval.i = atoi(magic_frontend_text);
		      FIXLOC;
                      return INT; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 125 "magic-interpreter.l"
{ magic_frontend_lval.i = strtol(magic_frontend_text + 2, NULL, 16);
		      FIXLOC;
                      return INT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 129 "magic-interpreter.l"
{ magic_frontend_lval.s = strdup(magic_frontend_text);
		            FIXLOC;
                            return ID; }
	YY_BREAK
case 81:
*yy_cp = (yy_hold_char); /* undo effects of setting up magic_frontend_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up magic_frontend_text again */
YY_RULE_SETUP
#line 133 "magic-interpreter.l"
/* Ignore comments */
	YY_BREAK
case 82:
*yy_cp = (yy_hold_char); /* undo effects of setting up magic_frontend_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up magic_frontend_text again */
YY_RULE_SETUP
#line 134 "magic-interpreter.l"
/* Ignore comments */
	YY_BREAK
case 83:
/* rule 83 can match eol */
YY_RULE_SETUP
#line 135 "magic-interpreter.l"
/* ignore whitespace */	
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 136 "magic-interpreter.l"
fprintf(stderr, "%s: Unexpected character in line %d\n", MAGIC_CONFIG_FILE, magic_frontend_lineno);
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 139 "magic-interpreter.l"
ECHO;
	YY_BREAK
#line 1416 "magic-interpreter-lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed magic_frontend_in at a new source and called
			 * magic_frontend_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = magic_frontend_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( magic_frontend_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * magic_frontend_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of magic_frontend_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					magic_frontend_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			magic_frontend_restart(magic_frontend_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) magic_frontend_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 238 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 238 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 237);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					magic_frontend_restart(magic_frontend_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( magic_frontend_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve magic_frontend_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    magic_frontend_lineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void magic_frontend_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        magic_frontend_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            magic_frontend__create_buffer(magic_frontend_in,YY_BUF_SIZE );
	}

	magic_frontend__init_buffer(YY_CURRENT_BUFFER,input_file );
	magic_frontend__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void magic_frontend__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		magic_frontend_pop_buffer_state();
	 *		magic_frontend_push_buffer_state(new_buffer);
     */
	magic_frontend_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	magic_frontend__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (magic_frontend_wrap()) processing, but the only time this flag
	 * is looked at is after magic_frontend_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void magic_frontend__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	magic_frontend_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE magic_frontend__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) magic_frontend_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in magic_frontend__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) magic_frontend_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in magic_frontend__create_buffer()" );

	b->yy_is_our_buffer = 1;

	magic_frontend__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with magic_frontend__create_buffer()
 * 
 */
    void magic_frontend__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		magic_frontend_free((void *) b->yy_ch_buf  );

	magic_frontend_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a magic_frontend_restart() or at EOF.
 */
    static void magic_frontend__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	magic_frontend__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then magic_frontend__init_buffer was _probably_
     * called from magic_frontend_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void magic_frontend__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		magic_frontend__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void magic_frontend_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	magic_frontend_ensure_buffer_stack();

	/* This block is copied from magic_frontend__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from magic_frontend__switch_to_buffer. */
	magic_frontend__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void magic_frontend_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	magic_frontend__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		magic_frontend__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void magic_frontend_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)magic_frontend_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in magic_frontend_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)magic_frontend_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in magic_frontend_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE magic_frontend__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) magic_frontend_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in magic_frontend__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	magic_frontend__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to magic_frontend_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       magic_frontend__scan_bytes() instead.
 */
YY_BUFFER_STATE magic_frontend__scan_string (yyconst char * yystr )
{
    
	return magic_frontend__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to magic_frontend_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE magic_frontend__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) magic_frontend_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in magic_frontend__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = magic_frontend__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in magic_frontend__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up magic_frontend_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		magic_frontend_text[magic_frontend_leng] = (yy_hold_char); \
		(yy_c_buf_p) = magic_frontend_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		magic_frontend_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int magic_frontend_get_lineno  (void)
{
        
    return magic_frontend_lineno;
}

/** Get the input stream.
 * 
 */
FILE *magic_frontend_get_in  (void)
{
        return magic_frontend_in;
}

/** Get the output stream.
 * 
 */
FILE *magic_frontend_get_out  (void)
{
        return magic_frontend_out;
}

/** Get the length of the current token.
 * 
 */
int magic_frontend_get_leng  (void)
{
        return magic_frontend_leng;
}

/** Get the current token.
 * 
 */

char *magic_frontend_get_text  (void)
{
        return magic_frontend_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void magic_frontend_set_lineno (int  line_number )
{
    
    magic_frontend_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see magic_frontend__switch_to_buffer
 */
void magic_frontend_set_in (FILE *  in_str )
{
        magic_frontend_in = in_str ;
}

void magic_frontend_set_out (FILE *  out_str )
{
        magic_frontend_out = out_str ;
}

int magic_frontend_get_debug  (void)
{
        return magic_frontend__flex_debug;
}

void magic_frontend_set_debug (int  bdebug )
{
        magic_frontend__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from magic_frontend_lex_destroy(), so don't allocate here.
     */

    /* We do not touch magic_frontend_lineno unless the option is enabled. */
    magic_frontend_lineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    magic_frontend_in = stdin;
    magic_frontend_out = stdout;
#else
    magic_frontend_in = (FILE *) 0;
    magic_frontend_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * magic_frontend_lex_init()
     */
    return 0;
}

/* magic_frontend_lex_destroy is for both reentrant and non-reentrant scanners. */
int magic_frontend_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		magic_frontend__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		magic_frontend_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	magic_frontend_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * magic_frontend_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *magic_frontend_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *magic_frontend_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void magic_frontend_free (void * ptr )
{
	free( (char *) ptr );	/* see magic_frontend_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 139 "magic-interpreter.l"



