#!/usr/bin/env bash 
# Apply a filter command to a set of files
set -eu

filter=$1; shift
trap 'rm -f "$arg.tmp"' EXIT
for arg
do
    echo apply-filter "$filter" "$arg"
    bash -c "set -o pipefail; $filter" < "$arg" > "$arg.tmp"
    maybe-mv "$arg.tmp" "$arg"
done
