#!/usr/bin/env python3
# -*- encoding: utf-8
##    bs-align.py - Filter to align trailing line continuations
##
##    Copyright ©2013 Ben Longbons <b.r.longbons@gmail.com>
##
##    This file is part of The Mana World (Athena server)
##
##    This program is free software: you can redistribute it and/or modify
##    it under the terms of the GNU General Public License as published by
##    the Free Software Foundation, either version 3 of the License, or
##    (at your option) any later version.
##
##    This program is distributed in the hope that it will be useful,
##    but WITHOUT ANY WARRANTY; without even the implied warranty of
##    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##    GNU General Public License for more details.
##
##    You should have received a copy of the GNU General Public License
##    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Settings.
pad = 1
align = 4
min_col = 8

import sys

lines = []

for line in sys.stdin:
    if line.endswith('\\\n'):
        lines.append(line[:-2].rstrip())
        continue
    if lines:
        # TODO: correctly handle tabs and multibyte characters
        tlen = max(len(l) for l in lines) + pad
        if tlen < min_col:
            tlen = min_col
        elif tlen % align:
            tlen += align - tlen % align
        for l in lines:
            sys.stdout.writelines([l, ' ' * (tlen - len(l)), '\\\n'])
        del lines[:]
    sys.stdout.write(line)
