#!/usr/bin/env bash
# this is the implementation of indenter -cpp
set -e
set -o pipefail
expand |
sed -e 's:^ *//:&&:' -e 's:^ *#://#:' |
indenter -ipp |
sed -e 's:^ *// *#:#:' -e 's:^\( *//\) *//:\1:' |
pp-indent |
bs-align
